Consensys/scribble

src/bin/scribble.ts, src/instrumenter/annotations.ts, test/integration/scribble/run/invalid.spec.ts, test/multifile_samples/inheritance1/C.sol, test/multifile_samples/inheritance1/flat.sol.expected, test/multifile_samples/inheritance1/propertyMap.json.expected, test/samples/if_succeeds_on_contract.invalid.sol, test/samples/if_succeeds_on_free_function.invalid.sol, test/samples/invariant_on_function.invalid.sol
- Isolated annotation parsing to `makeAnnotationFromMatch()` funtion for a better readability.
- Introduced `validateAnnotation()` method to check that created annotation is valid for the target. Moved rules from scribble executable module to this method to concentrate logic in a single place.
- Tweaked `findAnnotations()` to respect filtering in-place and do not trigger validation on filtered out annotations.
Regards.
=> Disallow if_succeeds annotation for contract definitions

.drone.yml
=> Boost tests by using NodeJS v12 for pipeline

src/ast_to_source_printer.ts, src/bin/scribble.ts, src/rewriter/import_directive.pegjs, src/rewriter/merge.ts, src/rewriter/sanity.ts, test/integration/multifile.spec.ts, test/multifile_samples/reexported_imports/flat.sol.expected, test/multifile_samples/reexported_imports/imp1.sol, test/multifile_samples/reexported_imports/imp2.sol, test/multifile_samples/reexported_imports/imp3.sol, test/multifile_samples/reexported_imports/main.sol, test/multifile_samples/reexported_imports/propertyMap.json.expected, test/multifile_samples/reexported_imports_05/flat.sol.expected, test/multifile_samples/reexported_imports_05/imp1.sol, test/multifile_samples/reexported_imports_05/imp2.sol, test/multifile_samples/reexported_imports_05/imp3.sol, test/multifile_samples/reexported_imports_05/main.sol, test/multifile_samples/reexported_imports_05/propertyMap.json.expected, test/unit/interposing.spec.ts
This pr adds support for re-exported imports and unit alias imports. E.g given the following 3 files:
```
A.sol
contract Foo {..}
B.sol
import "A.sol" as A;
import {Foo as Boo} from "A.sol";
C.sol
import {A as A1} from "B.sol";
import {Boo as Moo} from "B.sol";
import "B.sol";
contract Test{
A1.Foo x;
Moo y;
Boo z;
}
```
When re-writing in flat mode, all the different aliases for `Foo` - `A1.Foo`, `Boo`, `Moo` should just be rewritten to `Foo`:
```
pragma solidity 0.7.5;
contract Foo {...}
...
contract Test {
Foo internal x;
Foo internal y;
Foo internal z;
}
```
Notes:
- this PR also fixes a bug in the grammar for imports
- it introduces the `replaceNode` function in `scribble.ts`. That function should eventually be moved to solc-typed-ast.
=> Fixes to support re-exported imports and additional tests

src/bin/scribble.ts, src/instrumenter/instrument.ts, test/samples/userFunctions.instrumented.sol, test/unit/interposing.spec.ts
If we have a contract with user functions but no invariants:
```
/// define one() uint = 1
contract Foo {
}
```
Scribble will currently emit a bunch of extra unnecessary state invariant checker code, due to out-of-date detection code in `scribble.ts`:
```
pragma solidity 0.8.0;
/// Utility contract holding a stack counter
contract __scribble_ReentrancyUtils {
bool __scribble_out_of_contract = true;
}
/// define one() uint = 1
contract Foo is __scribble_ReentrancyUtils {
event AssertionFailed(string message);
/// Implementation of user function define one() uint256 = 1
function one() internal view returns (uint256) {
return 1;
}
/// Check only the current contract's state invariants
function __scribble_Foo_check_state_invariants_internal() internal {
}
/// Check the state invariant for the …
```
=> Don't emit empty invariant checkers on contracts with user functions

src/instrumenter/instrument.ts, src/instrumenter/state_var_instrumenter.ts, test/integration/src2srcmap.spec.ts, test/samples/if_assigned_complex.instrumented.sol, test/samples/if_assigned_inline_initializers.instrumented.sol, test/samples/if_assigned_primitive.instrumented.sol, test/samples/if_updated_aliasing.instrumented.sol, test/samples/if_updated_inline_initializers.instrumented.sol, test/samples/if_updated_primitive.instrumented.sol, test/samples/if_updated_tuples.instrumented.sol, test/samples/if_updated_unsafe.instrumented.sol, test/samples/if_updated_unsafe.sol
After 0.8.0 Solidity arithmetic becomes 'checked' by default. In order to:
1. Have consistent behavior with Scribble pre-0.8.0
2. Ensure that spec computation does not risk throwing additional errors
3. Make it easier to write specs about functions containing unchecked computation
We have decided that scribble specs will have **unchecked** semantics. I.e. they may silently overflow without reverting.
To implement this, we wrap all scribble instrumentation-related computation in `unchecked {}` blocks.
=> Wrap scribble computations in unchecked for Solidity >= 0.8.0

src/instrumenter/transpile.ts, test/samples/misc.instrumented.sol, test/samples/misc.sol
Fixes #27. When transpiling external function calls that use just an identifier (e.g. `foo(x)`), we need to convert those to member accesses (e.g. `this.foo(x)`).
=> Fix for #27 - external view function calls not transpiled correctly

.drone.yml, package.json, src/instrumenter/instrument.ts
Compiling of `let` statements in 0.8.x is broken in version 0.4.1. Specifically we were placing `old-` bindings in the unchecked block where `let-` bindings should be placed. This PR fixes this and makes CI run mocha tests in parallel to avoid timeouts.
=> Fix bug in 0.4.1 compilation of let statements in 0.8.x

src/instrumenter/annotations.ts, test/samples/misc.instrumented.sol, test/samples/misc.sol
This PR fixes #28. Essentially we make the first-pass regex that finds candidate annotations in docstrings match more-precisely to `define`-s that look like function definitions.
=> Fix for Issue #28

src/spec-lang/tc/typecheck.ts, test/unit/tc.spec.ts
Fixes https://github.com/ConsenSys/scribble/issues/33. The issue was that we were too aggressive in type-checking MemberAccess-es where the base was of type address or contract, terminating early and preventing code further down in `tcMemberAccess` from checkin if any `using for ...` declarations match the access. The fix is to just remove the early termination errors.
=> Fix for Issue #31: Failure with "using for" over address

src/instrumenter/interpose.ts
[NOTE: This PR should be merged after the forall PR #40]
In 0.8.x when we annotate a constructor, the resulting instrumented codedoesn't compile as the renamed constructor is missing its visibility. This is due to the fact that we forget to set `isConstructor` on the
renamed constructor to false, and as a result `solc-typed-ast` doesn't
print the visibility. Fix this.
=> Bug when instrumenting constructors in 0.8.x

src/rewriter/import_directive.pegjs, src/spec-lang/expr_grammar.pegjs
For last few weeks Scribble received several bigger updates, that were affecting grammar. We figured out that it would be simplier to improve grammars to make overall style a bit more readable for a future changes.
Tweaked `import_directive.pegjs` and `expr_grammar.pegjs`:
Regards.
=> Cleanup in grammars

package-lock.json, package.json, src/bin/scribble.ts, src/bin/scribble_cli.json, src/rewriter/flatten.ts
This PR:
1. Add support for `--compiler-settings` command line option. This options allows for a user to pass arbitrary settings to the Solidity compiler as a JSON string. (e.g. `--compiler-settings '{"optimizer": {"enabled": true, "runs": 200}}'` (note the use of single and double quotes). For more info see https://docs.soliditylang.org/en/latest/using-the-compiler.html#input-description. (Fixes #77)
2. Fixes a bug when merging multiple pragmas in flat mode. If we have pragmas with the same id in multiple files, then after flattening we would have multiple pragmas for the same id in the flat file, which causing compiler failures (this happens for example with `pragma experimental ABIEncoderV2`).
=> Add support for --compiler-settings command line option

package-lock.json, package.json, src/bin/scribble.ts
This PR changes scribble behavior to NOT require successful ir/bytecode generation when instrumenting in flat or files mode. This is done by only requiring ast,abi and userdoc output from the underlying solidity compiler. Note that successful bytecode generation is still required when instrumenting in json mode.
=> Change scribble to not always generate bytecode when compiling

src/instrumenter/interpose.ts, src/instrumenter/transpile.ts, src/instrumenter/utils.ts, src/rewriter/flatten.ts, src/util/misc.ts, test/samples/calldata_paramteres.instrumented.sol, test/samples/contract_decorated_ext_call.instrumented.sol, test/samples/contract_decorated_ext_callv05.instrumented.sol, test/samples/contract_pos_ext_call_fail.instrumented.sol, test/unit/interposing.spec.ts
This PR fixes #75.
Specifically it:
1. Changes the behavior of `interposeCall` to  obtain the original function arguments/returns from the callee type rather than the original definition. This avoids issues with public state var implementation for args/returns getters missing from solc-typed-ast
2. Change external call interposing to pass the receiver instead of a function pointer. This is an unrelated fix that will make our instrumentation more friendly to SMT verificaiton tools such as SMTChecker and solc-verify, that don't handle function pointers well yet.
=> Fix for #75

src/bin/scribble.ts, src/spec-lang/ast/declarations/annotation.ts, src/spec-lang/ast/declarations/if_assigned.ts, src/spec-lang/ast/declarations/if_updated.ts, src/spec-lang/ast/declarations/property.ts, src/spec-lang/ast/declarations/state_var_prop.ts, src/spec-lang/ast/declarations/user_function_definition.ts, src/spec-lang/expr_grammar.pegjs, test/unit/parser.spec.ts
NOTE: This PR depends on #112 . After that merges this should be re-targeted to develop.
This PR doesn't have many visible changes. It tweaks the grammar and the datatypes inside `SAnnotation` to allow adding more metadata tags other than just `:msg`. Closes #115
=> [WIP] Add proper annotation metadata

.gitignore, src/spec-lang/expr_grammar.pegjs, src/spec-lang/tc/builtins.ts, src/spec-lang/tc/internal_types/index.ts, src/spec-lang/tc/internal_types/variable_types.ts, src/spec-lang/tc/typecheck.ts, test/samples/encode.instrumented.sol, test/samples/encode.sol, test/unit/parser.spec.ts, test/unit/tc.spec.ts
This PR fixes #121  and #123 . Specifically:
1. Fix for #121  - tweak the grammar to support `forall`s inside boolean expressions without parenthesis. Add parsing tests
2. Fix for #123  - support the `abi.encode*` family of builtins. To do this adds a new internal `VariableTypes` type node, used to denote variable number of arguments for functions; Add typing definitions for the `abi.encode*` functions in `src/spec-lang/tc/builtins.ts`; Tweak `typecheck.ts` to handle type-checking of functions with variable number of arguments.
Note: We still don't support `abi.decode` as that additionally requires adding tuples to the scribble language.
=> Fixes for bugs #121 and #123

package-lock.json, src/spec-lang/expr_grammar.pegjs, test/unit/parser.spec.ts
This adds a small shorthand for annotation labels. Instead of having to write this:
```
#invariant {:msg "Invariant1"} ...;
```
Now you can just write:
```
#invariant "Invariant1" ...;
```
The old syntax is still supported.
=> Support annotation label short-hand with just a string

src/spec-lang/tc/typecheck.ts, test/unit/tc.spec.ts
=> Fix for #141

src/spec-lang/tc/semcheck.ts, test/samples/forall_maps.instrumented.sol, test/samples/forall_maps.sol, test/unit/sc.spec.ts
This PR disallows old expressions of the type `old(e)` where e is of type array or map. Note that `old(e[x])`is still allowed as long as its a primitive type. Fixes #150  and #152
=> Disallow arrays and maps in old()

src/bin/scribble.ts, src/spec-lang/tc/typecheck.ts
- Fixes #174
- Fixes #175 
Regards.
=> Allow structs to use bound library methods and fix imports in executable

src/spec-lang/expr_parser_header.ts
This PR fixes #181
- PR are still missing some test samples.
- We still should better formulate an error message for `SNoField` when user passes `UserDefinedType` instead of `PointerType`.
Regards.
=> Properly support user-defined types with unqualified names

.github/workflows/npm.yaml
- Added `npm.yaml` GitHub Actions workflow file to automate package publishing. Package should publish when release tag is created. For additional info refer to [the sample](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm).
- The `NPM_TOKEN` **should be set in repository secrets** in order to allow automation to publish package to NPM registry.
Regards.
=> Automate package publishing via GitHub Actions workflow

README.md
You can check the results [here](https://github.com/Consensys/scribble/blob/a2e23cf74fa29318d0b15dcfb3aba3646c264260/README.md).
Regards.
=> Tweak badges in README

src/instrumenter/instrumentation_context.ts, src/instrumenter/interpose.ts
Instrumentation (especially callsite interposing) may sometimes introduce variable declarations for types that are not in scope in a contract. Add functionality to accumulate new types that need to be imported at a particular source unit due to instrumentation and add those imports as needed
=> Fix missing imports caused due to instrumentation

src/instrumenter/instrument.ts, test/unit/interposing.spec.ts
We currently interpose on callsites inside view functions. The original reason for this is that we were worried about external view functions calling back into the contract and potentially getting inconsistent state. Specifically the scenario we were worried about was:
1. We are  in some non-view function F1 of contract C, that violates the invariant
2.  F1 calls F2 (internally), and F2 is a view function
3.  F2 calls (externally) F3 which is also view
4.  F3 calls back into C, and gets inconsistent state
5.  Inconsistent state gets propagated all the way back in to F1
However even if this happened, since the calls to F3 (and onwards) are all view, (and thus side-effect free), then the only thing that the inconsistent state of C can get propagate to is back to C itself. So logically this …
=> Dont interpose on callsites in view functions

package-lock.json, package.json, src/ast_to_source_printer.ts, src/bin/scribble.ts, src/instrumenter/annotations.ts, src/instrumenter/deprecated_warnings.ts, src/instrumenter/instrumentation_context.ts, src/spec-lang/ast/node.ts, src/util/json_output.ts, src/util/sources.ts, src/util/unicode.ts, test/integration/propertymap.spec.ts, test/integration/src2srcmap.spec.ts, test/integration/utils.ts, test/unit/interposing.spec.ts, test/unit/sc.spec.ts, test/unit/tc.spec.ts
This PR:
-  bumps solc-typed-ast to 18.1.0
- renames some changed unicode helpers
=> Bump solc-typed-ast to 18.1.0

src/instrumenter/annotations.ts, src/instrumenter/instrument.ts, test/samples/hardhat_test.instrumented.sol, test/samples/misc.instrumented.sol
=> Fix for #272
